---
kind: pipeline
name: icekramel CI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build
    image: archlinux:base-devel
    environment:
      patched_glibc: glibc-linux4-2.33-5-x86_64.pkg.tar.zst
      KBUILD_BUILD_USER: misaka
      KBUILD_BUILD_HOST: tp-workstation
    commands:
      - curl -LO "https://repo.archlinuxcn.org/x86_64/$patched_glibc" && bsdtar -C / -xvf "$patched_glibc"
      - echo -e "\n[archlinuxcn]\nServer = https://repo.archlinuxcn.org/\$arch" >> /etc/pacman.conf
      - pacman-key --init && pacman -Syy archlinuxcn-keyring --noconfirm
      - pacman -S android-sdk-build-tools bc cpio dtc git libyaml lib32-gcc-libs p7zip aarch64-linux-gnu-gcc arm-none-eabi-gcc --noconfirm
      - git clone https://github.com/alk3p/build-scripts /drone/build-tools/build-scripts --branch op7-r --depth 1
      - git clone https://github.com/alk3p/anykernel3 /drone/build-tools/anykernel --branch op7-r --depth 1
      - cd /drone/src
      - bash ../build-tools/build-scripts/build.sh upload
