---
kind: pipeline
name: icekramel CI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build
    image: alk3p/archlinux:kernel-devel
    environment:
      KBUILD_BUILD_USER: misaka
      KBUILD_BUILD_HOST: tp-workstation
    commands:
      - git clone https://github.com/alk3p/build-scripts /drone/build-tools/build-scripts --branch op7-r --depth 1
      - git clone https://github.com/alk3p/anykernel3 /drone/build-tools/anykernel --branch op7-r --depth 1
      - cd /drone/src
      - bash ../build-tools/build-scripts/build.sh upload
